### ISSUE TITLE
Can't execute with openSUSE Tumbleweed

### ISSUE THREAD

**Issue by deneb-alpha** [reisi007/Kotlin-SI-GUI#1]
java.io.IOException: Cannot run program "si-gui-desktop" (in directory "/home/deneb/QA/kotlin-si-gui/si-gui-desktop/bin"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at at.reisisoft.sigui.updater.Updater.startSiGui(Updater.java:129)
        at at.reisisoft.sigui.updater.Updater.main(Updater.java:67)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 3 more
Exception in thread "main" java.lang.IllegalStateException: Better exception handling needed!
        at at.reisisoft.sigui.updater.Updater.main(Updater.java:78)

java -version
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment (build 10+46-suse-1.2-x8664)
OpenJDK 64-Bit Server VM (build 10+46-suse-1.2-x8664, mixed mode)

**Comment by reisi007** [comment]
It MIGHT be enough to change on line https://github.com/reisi007/Kotlin-SI-GUI/blob/master/si-gui-updater/src/main/java/at/reisisoft/sigui/updater/Updater.java#L129

"si-gui-desktop" to "./"si-gui-desktop"

**Comment by deneb-alpha** [comment]
Works fine with Oracle Java installed. 
Probably there's something missing related to JavaFX with the available openJDK under openSUSE.

**Comment by reisi007** [comment]
@deneb-alpha There is a openjfx package, which adds JavaFX to the openjdk:
- https://packages.ubuntu.com/search?keywords=openjfx
- For openSUSE there does not seem to be a JavaFX package available: https://forums.opensuse.org/showthread.php/519171-OpenJFX-Package

Works with openjdk8 and installed openjfx.
