### ISSUE TITLE
Download error under Linux

### ISSUE THREAD

**Issue by deneb-alpha** [reisi007/Kotlin-SI-GUI#6]
**java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)**

Loading setings
Settings path: /home/deneb/QA/kotlin-si-gui/si-gui-desktop/bin/si-gui.settings.json
Update version clicked!
Storing settings
Open download menu
Unexpected exception!
java.lang.UnsupportedOperationException: Retrieving groups by name is not supported on this platform.
        at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:28)
        at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:260)
        at kotlin.text.jdk8.RegexExtensionsJDK8Kt.get(RegexExtensions.kt:33)
        at at.reisisoft.NamingUtils.extractName(NamingUtils.kt:13)
        at at.reisisoft.sigui.ui.MainUIController$initInstallation$5.changed(MainUIController.kt:496)
        at at.reisisoft.sigui.ui.MainUIController$initInstallation$5.changed(MainUIController.kt:43)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
        at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
        at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
        at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
        at javafx.base/javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
        at javafx.controls/javafx.scene.control.Labeled.setText(Labeled.java:147)
        at at.reisisoft.sigui.ui.MainUIController$downloadManagerDelegate$1$$special$$inlined$apply$lambda$1$2.invoke(MainUIController.kt:412)
        at at.reisisoft.sigui.ui.MainUIController$downloadManagerDelegate$1$$special$$inlined$apply$lambda$1$2.invoke(MainUIController.kt:394)
        at at.reisisoft.ui.JavaFXKt$sam$java_lang_Runnable$0.run(JavaFX.kt)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by reisi007** [comment]
Should be fixed, closing
